[package]
name = "pcapan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqprs = "1.5.1"
chrono = "0.4.31"
itertools = "0.12.0"
libc = "0.2.150"
pcap = "1.1.0"
tokio = "1.35.0"
